import { SquareType, PlayerColor } from './types.ts';
import type { BoardSquare } from './types.ts';

// The finalized 48-block board layout
export const boardLayout: Readonly<BoardSquare[]> = [
    { index: 0, coords: { row: 2, col: 4 }, type: SquareType.SafeZone, value: 0, ownerColor: PlayerColor.Blue },
    { index: 1, coords: { row: 2, col: 3 }, type: SquareType.Runs, value: 1 },
    { index: 2, coords: { row: 1, col: 3 }, type: SquareType.Wicket, value: 0 },
    { index: 3, coords: { row: 0, col: 3 }, type: SquareType.Runs, value: 2 },
    { index: 4, coords: { row: 0, col: 2 }, type: SquareType.Wicket, value: 0 },
    { index: 5, coords: { row: 0, col: 1 }, type: SquareType.Runs, value: 4 },
    { index: 6, coords: { row: 0, col: 0 }, type: SquareType.Runs, value: 6 },
    { index: 7, coords: { row: 1, col: 0 }, type: SquareType.Runs, value: 2 },
    { index: 8, coords: { row: 2, col: 0 }, type: SquareType.Runs, value: 1 },
    { index: 9, coords: { row: 3, col: 0 }, type: SquareType.Extra, value: 0 },
    { index: 10, coords: { row: 3, col: 1 }, type: SquareType.Runs, value: 3 },
    { index: 11, coords: { row: 3, col: 2 }, type: SquareType.DotBall, value: 0 },
    { index: 12, coords: { row: 4, col: 2 }, type: SquareType.SafeZone, value: 0, ownerColor: PlayerColor.Yellow },
    { index: 13, coords: { row: 5, col: 2 }, type: SquareType.Runs, value: 1 },
    { index: 14, coords: { row: 5, col: 1 }, type: SquareType.Wicket, value: 0 },
    { index: 15, coords: { row: 5, col: 0 }, type: SquareType.Runs, value: 2 },
    { index: 16, coords: { row: 6, col: 0 }, type: SquareType.Wicket, value: 0 },
    { index: 17, coords: { row: 7, col: 0 }, type: SquareType.Runs, value: 4 },
    { index: 18, coords: { row: 8, col: 0 }, type: SquareType.Runs, value: 6 },
    { index: 19, coords: { row: 8, col: 1 }, type: SquareType.Runs, value: 2 },
    { index: 20, coords: { row: 8, col: 2 }, type: SquareType.Runs, value: 1 },
    { index: 21, coords: { row: 8, col: 3 }, type: SquareType.Extra, value: 0 },
    { index: 22, coords: { row: 7, col: 3 }, type: SquareType.Runs, value: 3 },
    { index: 23, coords: { row: 6, col: 3 }, type: SquareType.DotBall, value: 0 },
    { index: 24, coords: { row: 6, col: 4 }, type: SquareType.SafeZone, value: 0, ownerColor: PlayerColor.Green },
    { index: 25, coords: { row: 6, col: 5 }, type: SquareType.Runs, value: 1 },
    { index: 26, coords: { row: 7, col: 5 }, type: SquareType.Wicket, value: 0 },
    { index: 27, coords: { row: 8, col: 5 }, type: SquareType.Runs, value: 2 },
    { index: 28, coords: { row: 8, col: 6 }, type: SquareType.Wicket, value: 0 },
    { index: 29, coords: { row: 8, col: 7 }, type: SquareType.Runs, value: 4 },
    { index: 30, coords: { row: 8, col: 8 }, type: SquareType.Runs, value: 6 },
    { index: 31, coords: { row: 7, col: 8 }, type: SquareType.Runs, value: 2 },
    { index: 32, coords: { row: 6, col: 8 }, type: SquareType.Runs, value: 1 },
    { index: 33, coords: { row: 5, col: 8 }, type: SquareType.Extra, value: 0 },
    { index: 34, coords: { row: 5, col: 7 }, type: SquareType.Runs, value: 3 },
    { index: 35, coords: { row: 5, col: 6 }, type: SquareType.DotBall, value: 0 },
    { index: 36, coords: { row: 4, col: 6 }, type: SquareType.SafeZone, value: 0, ownerColor: PlayerColor.Purple },
    { index: 37, coords: { row: 3, col: 6 }, type: SquareType.Runs, value: 1 },
    { index: 38, coords: { row: 3, col: 7 }, type: SquareType.Wicket, value: 0 },
    { index: 39, coords: { row: 3, col: 8 }, type: SquareType.Runs, value: 2 },
    { index: 40, coords: { row: 2, col: 8 }, type: SquareType.Wicket, value: 0 },
    { index: 41, coords: { row: 1, col: 8 }, type: SquareType.Runs, value: 4 },
    { index: 42, coords: { row: 0, col: 8 }, type: SquareType.Runs, value: 6 },
    { index: 43, coords: { row: 0, col: 7 }, type: SquareType.Runs, value: 2 },
    { index: 44, coords: { row: 0, col: 6 }, type: SquareType.Runs, value: 1 },
    { index: 45, coords: { row: 0, col: 5 }, type: SquareType.Extra, value: 0 },
    { index: 46, coords: { row: 1, col: 5 }, type: SquareType.Runs, value: 3 },
    { index: 47, coords: { row: 2, col: 5 }, type: SquareType.DotBall, value: 0 },
];